import { useEffect, useRef } from 'react';
import './StoryPlayer.scss';
import { RotateCcw, Sparkles, Bookmark, BookmarkCheck, BookOpen } from 'lucide-react';
import { useStoryStore } from '../../store/useStoryStore';
import { useSettingsStore } from '../../store/useSettingsStore';
import { useAutoHide } from '../../hooks/useAutoHide';
import { useStoryActions } from '../../hooks/useStoryActions';
import { useSaveSession } from '../../hooks/useSaveSession';
import { bionicEncode } from '../../utils/bionicEncode';

const PROVIDER_LABELS: Record<string, string> = {
  openrouter:      'Google · Gemini 2.0 Flash',
  groq:            'Groq · Llama 3.3 70b',
  'groq-fallback': 'Groq · Llama 3.1 8b',
};

const FONT_SIZE_MAP = {
  sm: 'var(--font-size-sm)',
  md: 'var(--font-size-md)',
  lg: 'var(--font-size-lg)',
  xl: 'var(--font-size-xl)',
};

function parseStory(raw: string): { title: string; paragraphs: string[] } {
  const lines = raw.split('\n');
  const title = lines[0] ?? '';
  const body = lines.slice(1).join('\n');
  const paragraphs = body
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter(Boolean);
  return { title, paragraphs };
}

export function StoryPlayer() {
  const { storyText, status, reset, isFromHistory, selectedThemes, pov, withCharacter, withDialogue, storyLength, customPrompt, provider } = useStoryStore();
  const isLoading = status === 'loading';
  const { font, fontSize, bionicReading } = useSettingsStore();
  const { generate, continueStory } = useStoryActions();
  const { saveStatus, save } = useSaveSession();
  const scrollRef = useRef<HTMLDivElement>(null);
  const controlsVisible = useAutoHide(10_000);

  useEffect(() => {
    if (scrollRef.current && status === 'streaming') {
      scrollRef.current.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
    }
  }, [storyText, status]);

  const { title, paragraphs } = parseStory(storyText);
  const bodyStyle = { fontFamily: `'${font}', Georgia, serif`, fontSize: FONT_SIZE_MAP[fontSize] };
  const isSaved = saveStatus === 'saved';

  return (
    <div className="story-player" ref={scrollRef}>
      {title && <h1 className="story-player__title">{title}</h1>}

      <div className="story-player__body" style={bodyStyle}>
        {paragraphs.map((p, i) => {
          const isLast = i === paragraphs.length - 1;
          if (bionicReading) {
            return (
              <p
                key={i}
                className="story-player__paragraph"
                dangerouslySetInnerHTML={{ __html: bionicEncode(p) }}
              />
            );
          }
          return (
            <p key={i} className="story-player__paragraph">
              {p}
              {isLast && status === 'streaming' && (
                <span className="story-player__cursor" aria-hidden />
              )}
            </p>
          );
        })}

        {bionicReading && status === 'streaming' && (
          <span className="story-player__cursor" aria-hidden />
        )}

        {status === 'done' && (
          <>
            <div className="story-player__the-end" aria-hidden>
              <span className="story-player__the-end-rule" />
              <span className="story-player__the-end-text">The End</span>
              <span className="story-player__the-end-rule" />
            </div>
            {provider && (
              <p className="story-player__provider" aria-label={`Generated by ${PROVIDER_LABELS[provider] ?? provider}`}>
                {PROVIDER_LABELS[provider] ?? provider}
              </p>
            )}
          </>
        )}
      </div>

      {(status === 'done' || isLoading) && (
        <div className={`story-player__end ${controlsVisible ? '' : 'is-hidden'}`}>

          {isLoading ? (
            <div className="story-player__loading-dots" aria-label="Generating…">
              <span /><span /><span />
            </div>
          ) : (
            <>
              {/* Primary: save — most important action after finishing a story */}
              {!isFromHistory && (
                <button
                  className={`story-player__btn story-player__btn--primary ${isSaved ? 'is-saved' : ''} ${saveStatus === 'error' ? 'is-error' : ''}`}
                  onClick={() => !isSaved && save(selectedThemes, storyText, customPrompt, provider)}
                  disabled={saveStatus === 'saving' || isSaved}
                  aria-label={isSaved ? 'Story saved' : 'Save this story'}
                >
                  {isSaved
                    ? <><BookmarkCheck size={16} strokeWidth={1.5} /> Saved</>
                    : saveStatus === 'saving'
                      ? <><Bookmark size={16} strokeWidth={1.5} /> Saving…</>
                      : saveStatus === 'error'
                        ? <><Bookmark size={16} strokeWidth={1.5} /> Save failed — tap to retry</>
                        : <><Bookmark size={16} strokeWidth={1.5} /> Save story</>
                  }
                </button>
              )}

              {/* Secondary actions row */}
              <div className="story-player__btn-row">
                {!isFromHistory && (
                  <button
                    className="story-player__btn story-player__btn--secondary"
                    onClick={() => {
                      const paras = storyText.split(/\n\n+/).filter(Boolean);
                      const context = paras.slice(-3).join('\n\n');
                      continueStory(selectedThemes, pov, withCharacter, withDialogue, storyLength, context, customPrompt);
                    }}
                    aria-label="Continue the story"
                  >
                    <BookOpen size={14} strokeWidth={1.5} />
                    Continue
                  </button>
                )}
                {!isFromHistory && (
                  <button
                    className="story-player__btn story-player__btn--secondary"
                    onClick={() => generate(selectedThemes, pov, withCharacter, withDialogue, storyLength, customPrompt)}
                    aria-label="Generate another story with the same settings"
                  >
                    <Sparkles size={14} strokeWidth={1.5} />
                    Generate again
                  </button>
                )}
                <button
                  className="story-player__btn story-player__btn--ghost"
                  onClick={reset}
                  aria-label="Start a new story"
                >
                  <RotateCcw size={14} strokeWidth={1.5} />
                  New story
                </button>
              </div>
            </>
          )}

        </div>
      )}
    </div>
  );
}
